Ville:
    type: entity
    table: ville
    indexes:
        FKVille684553:
            columns:
                - ID_Pays
    id:
        idVille:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID_Ville
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: Nom
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Description
    manyToOne:
        idPays:
            targetEntity: Pays
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_Pays:
                    referencedColumnName: ID_Pays
            orphanRemoval: false
    manyToMany:
        idItineraire:
            targetEntity: Itineraire
            cascade: {  }
            mappedBy: idVille
            inversedBy: null
            joinTable: null
            orderBy: null
        idOffrep:
            targetEntity: OffreProfessionnelle
            cascade: {  }
            mappedBy: null
            inversedBy: idVille
            joinTable:
                name: ville_offre_professionnelle
                joinColumns:
                    -
                        name: ID_Ville
                        referencedColumnName: ID_Ville
                inverseJoinColumns:
                    -
                        name: ID_OffreP
                        referencedColumnName: ID_OffreP
            orderBy: null
    lifecycleCallbacks: {  }
