Newsletter:
    type: entity
    table: newsletter
    id:
        idNewsletter:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID_NewsLetter
            generator:
                strategy: IDENTITY
    fields:
        sujet:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Sujet
        message:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Message
        dateAjout:
            type: date
            nullable: true
            comment: ''
            column: Date_Ajout
    lifecycleCallbacks: {  }
